name: Secrets workflow

on:
    #workflow_dispatch: #okidamo adhoc, kad mi zelimo
    pull_request:
        branches: ["main"]

env:
    API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GithubActionsDotNet.Api.csproj"

jobs:
    secrets:
        name: Secrets Demo
        runs-on: ubuntu-latest
        env: #job specific variable
            JOB_NAME: "secrets"

        steps:
        - name: echo environmet variable
          run: echo "The value of ${{secrets.SECRET_API_KEY}} is $API_CSPROJ_PATH"


